parameters:
  failOnError: true
  progressToStdout: true

jobs:
  - type: context
    parameters:
      name: "Default Context"
      urls:
      - "http://${ZAP_TARGET_HOST}:8386/.*"
  - type: openapi
    parameters:
      file: /zap/wrk/openapi.json

  - type: spider
    parameters:
      maxDuration: 1

  - type: passiveScan-wait

  - type: activeScan
    parameters:
      policy: Default Policy

  - type: report
    parameters:
      reportDir: .
      reportFile: report_html.html
      reportTitle: "ZAP API Scan"
      template: traditional-html