env:
  contexts:
    - name: identity-api
      urls:
        - http://localhost:8386
      includePaths:
        - http://localhost:8386/.*

jobs:
  - type: openapi
    parameters:
      targetUrl: http://localhost:8386
      apiUrl: http://localhost:8386/api-docs
    context: identity-api

  - type: spider
    parameters:
      context: identity-api
      maxDuration: 2

  - type: passiveScan-wait

  - type: activeScan
    parameters:
      policy: Default Policy
    context: identity-api

  - type: report
    parameters:
      reportDir: /zap/reports
      reportFile: zap-report.html
      reportTitle: ZAP API Scan
      template: traditional-html
