env:
  contexts:
    - name: identity-api
      urls:
        - http://localhost:8386

parameters:
  failOnError: true
  progressToStdout: true

jobs:
  - type: openapi
    context: identity-api
    parameters:
      file: openapi.json

  - type: spider
    context: identity-api
    parameters:
      maxDuration: 1

  - type: passiveScan-wait

  - type: activeScan
    context: identity-api
    parameters:
      policy: Default Policy

  - type: report
    parameters:
      reportDir: .
      reportFile: report_html.html
      reportTitle: "ZAP API Scan"
      template: traditional-html
