env:
  contexts:
    - name: identity-api
      urls:
        - http://localhost:8386

parameters:
  failOnError: true
  progressToStdout: true

jobs:
  - type: openapi
    parameters:
      targetUrl: http://localhost:8386
      apiUrl: http://localhost:8386/api-docs

  - type: spider
    parameters:
      context: identity-api
      maxDuration: 2

  - type: passiveScan-wait

  - type: activeScan
    parameters:
      policy: Default Policy

  - type: report
    parameters:
      reportDir: /zap/wrk
      reportFile: report.html
      reportTitle: "ZAP API Scan"
      template: traditional-html