env:
  contexts:
    - name: identity-api
      urls:
        - http://localhost:8386

parameters:
  failOnError: false
  progressToStdout: true

jobs:
  - type: script
    name: Run API1 Test
    parameters:
      action: run
      type: httpsender
      engine: JavaScript
      file: /zap/scripts/API1.js

  - type: script
    name: Run API1-2 Test
    parameters:
      action: run
      type: httpsender
      engine: JavaScript
      file: /zap/scripts/API1-2.js

  - type: script
    name: Run API3 Test
    parameters:
      action: run
      type: httpsender
      engine: JavaScript
      file: /zap/scripts/API3.js

  - type: script
    name: Run API3-2 Test
    parameters:
      action: run
      type: httpsender
      engine: JavaScript
      file: /zap/scripts/API3-2.js

  - type: openapi
    parameters:
      targetUrl: http://localhost:8386
      apiUrl: http://localhost:8386/api-docs

  - type: openapi
    parameters:
      targetUrl: http://localhost:8386
      apiUrl: http://localhost:8386/api-docs

  - type: passiveScan-wait

  - type: report
    parameters:
      reportDir: /zap/wrk
      reportFile: zap-report.html
      template: traditional-html
      reportTitle: "ZAP Scan for API OWASP Top 10"
