env:
  contexts:
    - name: identity-api
      urls:
        - http://localhost:8386

parameters:
  failOnError: true
  progressToStdout: true

jobs:
  - type: script
    name: Add API1 Script
    parameters:
      action: add
      type: standalone
      engine: JavaScript
      name: API1
      file: /zap/scripts/API1.js

  - type: script
    name: Run API1 Script
    parameters:
      action: run
      name: API1

  - type: script
    name: Add API1-2 Script
    parameters:
      action: add
      type: standalone
      engine: JavaScript
      name: API1-2
      file: /zap/scripts/API1-2.js

  - type: script
    name: Run API1-2 Script
    parameters:
      action: run
      name: API1-2

  - type: script
    name: Add API3 Script
    parameters:
      action: add
      type: standalone
      engine: JavaScript
      name: API3
      file: /zap/scripts/API3.js

  - type: script
    name: Run API3 Script
    parameters:
      action: run
      name: API3

  - type: script
    name: Add API3-2 Script
    parameters:
      action: add
      type: standalone
      engine: JavaScript
      name: API3-2
      file: /zap/scripts/API3-2.js

  - type: script
    name: Run API3-2 Script
    parameters:
      action: run
      name: API3-2

  - type: openapi
    parameters:
      targetUrl: http://localhost:8386
      apiUrl: http://localhost:8386/api-docs

  - type: report
    parameters:
      reportDir: /zap/wrk
      reportFile: zap-report.html
      template: traditional-html
      reportTitle: ZAP Scan for API OWASP Top 10