env:
  contexts:
    - name: identity-api
      urls:
        - http://localhost:8386

parameters:
  failOnError: true
  progressToStdout: true

jobs:
  - type: openapi
    parameters:
      targetUrl: http://localhost:8386
      apiUrl: http://localhost:8386/api-docs

  - type: passiveScan-wait

  - type: report
    parameters:
      template: traditional-html
      reportTitle: ZAP API Scan
      reportDir: /zap/wrk
      reportFile: zap-report.html