name: Build and Test Spring Boot App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  JWT_SIGNER_KEY: ${{ secrets.JWT_SIGNER_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run unit tests
        run: mvn test

      # Optional: Kiểm tra chất lượng mã (ví dụ Checkstyle)
      # - name: Run Checkstyle
      #   run: mvn checkstyle:check

      # Optional: Upload artifact nếu muốn deploy
      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: spring-boot-app
      #     path: target/*.jar
